version: "3.8"

services:
  #  client:
  #    container_name: docker-react-c
  #    image: docker-react-i
  #    build:
  #      context: ./client
  #    ports:
  #      - "3000:3000"
  #
  #  server:
  #    container_name: docker-express-c
  #    image: docker-express-i
  #    build:
  #      context: ./server
  #    ports:
  #      - "8888:8888"

  db:
    image: postgres
    container_name: docker-postgres-c
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

  adminer:
    image: adminer
    container_name: docker-adminer-c
    restart: always
    ports:
      - "8080:8080"
